[package]
name = "tailwind-error"
version = "1.0.1"
authors = ["Aster <192607617@qq.com>"]
description = "Awsl Error Handlers"
repository = "https://github.com/notedge/notedown-rs/tree/master/projects/notedown-ast"
documentation = "https://docs.rs/tailwind-error"
categories = []
keywords = ["error", "tailwind"]
readme = "Readme.md"
license = "MPL-2.0"
edition = "2021"

[dependencies]
url = "2.2.2"
yggdrasil-shared = { version = "0.2.1", default-features = false }
# 3rd parts
num = { version = "0.4.0", optional = true }
rust_decimal = { version = "1.19.0", optional = true }
pest = { version = "2.1.3", optional = true }
globset = { version = "0.4.8", optional = true }
lsp-types = { version = "0.91.1", optional = true }
chrono = { version = "0.4.19", optional = true }

[dev-dependencies]

[features]
default = []
lsp = ["lsp-types", "yggdrasil-shared/lsp-types"]

[package.metadata.docs.rs]
all-features = true
